### ISSUE TITLE
add php_version in manual.json

### ISSUE THREAD

**Issue by Extor** [simtechdev/cartomatic#5]
I offer add variable `php_version` in `provision/config/manual.json`. It will be easier to install the appropriate php version for the environment.

**Comment by gongled** [comment]
Sounds good to me. Could you prepare pull request?

**Comment by Extor** [comment]
ok.

**Comment by Extor** [comment]
Create PR #6 to develop  branch

**Comment by gongled** [comment]
Thanks! Merged.
